### ISSUE TITLE
Nature's Aura causes 1.16.4 server crash

### ISSUE THREAD

**Issue by binksayres** [Ellpeck/NaturesAura#179]
After updating Direpack to 1.3.1, received following message:
 
 Mod File: NaturesAura-33.3.jar
        Failure message: Nature's Aura (naturesaura) encountered an error during the error event phase
                java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: de/ellpeck/naturesaura/api/render/IVisualizable
        Mod Version: 33.3
        Mod Issue URL: https://github.com/Ellpeck/NaturesAura
        Exception message: java.lang.ClassNotFoundException: de.ellpeck.naturesaura.api.render.IVisualizable

Stack Traces:

-- MOD naturesaura --
Details:
        Caused by 0: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: de/ellpeck/naturesaura/api/render/IVisualizable
                at de.ellpeck.naturesaura.reg.ModRegistry.registerEntities(ModRegistry.java:288) ~[naturesaura:33.3] {re:classloading}
                at net.minecraftforge.eventbus.ASMEventHandler_214_ModRegistry_registerEntities_Register.invoke(.dynamic) ~[?:?] {}
                at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:mixin,re:classloading}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
                at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
                at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
                at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[forge:?] {re:classloading}
                at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
                at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?] {re:classloading}
                at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
                at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
                at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
                at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1] {}
                at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
                at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
                at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
                at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.36.jar:?] {}
                at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.36.jar:?] {}
                at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.36.jar:?] {}

        Caused by 1: java.lang.NoClassDefFoundError: de/ellpeck/naturesaura/api/render/IVisualizable
                at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_271] {}
                at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.6.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271] {}
                at de.ellpeck.naturesaura.reg.ModRegistry.registerEntities(ModRegistry.java:288) ~[naturesaura:33.3] {re:classloading}
                at net.minecraftforge.eventbus.ASMEventHandler_214_ModRegistry_registerEntities_Register.invoke(.dynamic) ~[?:?] {}
                at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:mixin,re:classloading}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
                at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
                at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
                at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[forge:?] {re:classloading}
                at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
                at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?] {re:classloading}
                at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
                at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
                at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
                at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1] {}
                at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
                at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
                at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
                at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.36.jar:?] {}
                at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.36.jar:?] {}
                at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.36.jar:?] {}

        Mod File: NaturesAura-33.3.jar
        Failure message: Nature's Aura (naturesaura) encountered an error during the error event phase
                java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: de/ellpeck/naturesaura/api/render/IVisualizable
        Mod Version: 33.3
        Mod Issue URL: https://github.com/Ellpeck/NaturesAura
        Exception message: java.lang.ClassNotFoundException: de.ellpeck.naturesaura.api.render.IVisualizable
Stacktrace:
        at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_271] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.6.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271] {}
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_271] {}
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.0.6.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271] {}
        at de.ellpeck.naturesaura.reg.ModRegistry.registerEntities(ModRegistry.java:288) ~[naturesaura:33.3] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_214_ModRegistry_registerEntities_Register.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:mixin,re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
        at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.36.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.36.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.36.jar:?] {}

-- System Details --
Details:
        Minecraft Version: 1.16.4
        Minecraft Version ID: 1.16.4
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_271, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 2515452920 bytes (2398 MB) / 4294967296 bytes (4096 MB) up to 6442450944 bytes (6144 MB)
        CPUs: 12
        JVM Flags: 4 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx6144M -Xms4096M
        ModLauncher: 8.0.6+85+master.325de55
        ModLauncher launch target: fmlserver
        ModLauncher naming: srg
        ModLauncher services:
                /mixin-0.8.2.jar mixin PLUGINSERVICE
                /eventbus-3.0.5-service.jar eventbus PLUGINSERVICE
                /forge-1.16.4-35.1.36.jar object_holder_definalize PLUGINSERVICE
                /forge-1.16.4-35.1.36.jar runtime_enum_extender PLUGINSERVICE
                /accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE
                /forge-1.16.4-35.1.36.jar capability_inject_definalize PLUGINSERVICE
                /forge-1.16.4-35.1.36.jar runtimedistcleaner PLUGINSERVICE
                /mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE
                /forge-1.16.4-35.1.36.jar fml TRANSFORMATIONSERVICE
        FML: 35.1
        Forge: net.minecraftforge:35.1.36
        FML Language Providers:
                javafml@35.1
                minecraft@1

**Comment by binksayres** [comment]
This one was fully on my end.  Between my first run and second run, somehow this mod was corrupted.  Replacing the jar file with a known working version (from the client that actually loaded) resulted in the server running successfully.

Closing Issue.
